- name: Set environmental variables
  blockinfile:
      path: $HOME/.bash_profile
      create: yes
      block: |
              JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::")
              export JAVA_HOME
              PATH=$PATH:$JAVA_HOME/bin
              export PATH
      marker: ""
